Text Preprocessing->Padding -> word2Vec(Embedding)

In [1]:
from tensorflow.keras.preprocessing.text import one_hot

2025-01-23 03:42:13.047198: I external/local_xla/xla/tsl/cuda/cudart_stub.cc:32] Could not find cuda drivers on your machine, GPU will not be used.
2025-01-23 03:42:13.220461: I external/local_xla/xla/tsl/cuda/cudart_stub.cc:32] Could not find cuda drivers on your machine, GPU will not be used.
2025-01-23 03:42:13.393659: E external/local_xla/xla/stream_executor/cuda/cuda_fft.cc:485] Unable to register cuFFT factory: Attempting to register factory for plugin cuFFT when one has already been registered
2025-01-23 03:42:13.549008: E external/local_xla/xla/stream_executor/cuda/cuda_dnn.cc:8454] Unable to register cuDNN factory: Attempting to register factory for plugin cuDNN when one has already been registered
2025-01-23 03:42:13.590435: E external/local_xla/xla/stream_executor/cuda/cuda_blas.cc:1452] Unable to register cuBLAS factory: Attempting to register factory for plugin cuBLAS when one has already been registered
2025-01-23 03:42:16.423943: W tensorflow/compiler/tf2tensorrt/utils/p

In [2]:
msg= ['I play football',
     'I play chess', 
     'I study computer science',
     'It is too late to wake up',
     'Go to sleep',
     'I am a good developer',
     'I love drinking coffee',
     'understand the meaning of words']

In [3]:
msg

['I play football',
 'I play chess',
 'I study computer science',
 'It is too late to wake up',
 'Go to sleep',
 'I am a good developer',
 'I love drinking coffee',
 'understand the meaning of words']

In [4]:
voc_size = 500

In [6]:
onehot_repr = [one_hot(words, voc_size)for words in msg]
print(onehot_repr)

[[491, 50, 136], [491, 50, 261], [491, 53, 425, 150], [67, 320, 194, 150, 117, 224, 476], [390, 117, 380], [491, 259, 72, 426, 328], [491, 167, 369, 384], [299, 155, 233, 389, 186]]


In [14]:
from tensorflow.keras.layers import Embedding
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.models import Sequential
import numpy as np

In [15]:
msg_lenght = 8
embedded_docs = pad_sequences(onehot_repr, padding = 'pre', maxlen = msg_lenght)
print(embedded_docs)`

[[  0   0   0   0   0 491  50 136]
 [  0   0   0   0   0 491  50 261]
 [  0   0   0   0 491  53 425 150]
 [  0  67 320 194 150 117 224 476]
 [  0   0   0   0   0 390 117 380]
 [  0   0   0 491 259  72 426 328]
 [  0   0   0   0 491 167 369 384]
 [  0   0   0 299 155 233 389 186]]


In [16]:
# 10 features dimension
dim = 10

In [18]:
model=Sequential()
model.add(Embedding(voc_size, dim, input_length= msg_lenght))
model.compile('adam', 'mse')

/home/kuki/anaconda3/lib/python3.11/site-packages/keras/src/layers/core/embedding.py:90: UserWarning: Argument `input_length` is deprecated. Just remove it.
  warnings.warn(


In [19]:
model.summary()

Model: "sequential_1"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ embedding_1 (Embedding)         │ ?                      │   0 (unbuilt) │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 0 (0.00 B)

 Trainable params: 0 (0.00 B)

 Non-trainable params: 0 (0.00 B)

In [21]:
embedded_docs[0]

array([  0,   0,   0,   0,   0, 491,  50, 136], dtype=int32)

In [22]:
model.predict(embedded_docs[0])

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 369ms/step


array([[-0.02324705, -0.042694  ,  0.00905776, -0.01349924, -0.01756923,
        -0.00548046, -0.0010945 , -0.04195472, -0.04915377, -0.01859315],
       [-0.02324705, -0.042694  ,  0.00905776, -0.01349924, -0.01756923,
        -0.00548046, -0.0010945 , -0.04195472, -0.04915377, -0.01859315],
       [-0.02324705, -0.042694  ,  0.00905776, -0.01349924, -0.01756923,
        -0.00548046, -0.0010945 , -0.04195472, -0.04915377, -0.01859315],
       [-0.02324705, -0.042694  ,  0.00905776, -0.01349924, -0.01756923,
        -0.00548046, -0.0010945 , -0.04195472, -0.04915377, -0.01859315],
       [-0.02324705, -0.042694  ,  0.00905776, -0.01349924, -0.01756923,
        -0.00548046, -0.0010945 , -0.04195472, -0.04915377, -0.01859315],
       [ 0.03345025,  0.00055062, -0.04758108, -0.00494234,  0.0116505 ,
        -0.04301015, -0.03970891, -0.01027477, -0.04810251, -0.03618366],
       [-0.00237696,  0.00100207,  0.03953755,  0.00569825, -0.00098077,
         0.03112057, -0.00123408, -0.00965445